name: Default

on:
  push:
    branches-ignore:
      - master

jobs:
  check-gradle-version:
    name: Check Gradle version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: madhead/check-gradle-version@v1
    continue-on-error: true

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/wrapper-validation-action@v3
      - uses: gradle/gradle-build-action@v3
        with:
          arguments: check
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          retention-days: 1
          path: |
            **/build/reports
            **/build/test-results

  test-publish:
    name: Publish test results
    runs-on: ubuntu-latest
    needs:
      - unit-test
    if: always()
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: test-results
      - uses: mikepenz/action-junit-report@v4
        with:
          report_paths: '**/test-results/**/TEST-*.xml'
