name: Pages

on:
  push:
    branches:
      - master

jobs:
  dokka:
    name: Build the Dokka docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: gradle/actions/wrapper-validation@v3
      - uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}
      - run: ./gradlew dokkaHtmlMultiModule
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/dokka/htmlMultiModule

  deploy-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs:
      - dokka
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
